/**
 * Teacher Q&A generation (SPEC-APP.md §7.3): per-chunk grounded training
 * pairs generated by calling a Claude API "teacher" model, resumable batch
 * runner, and the manifest/review artifacts a run produces.
 */
import type { Chunk } from "../types.js";

/** One candidate (question, answer) pair grounded in a single source chunk. */
export interface QAPair {
  question: string;
  answer: string;
  /** The chunk_id(s) the answer cites. Every id here must be the source
   * chunk's own chunk_id — an answer citing a different chunk is rejected. */
  cited_chunk_ids: string[];
}

/** A candidate entry from the teacher's response that failed parsing,
 * shape validation, or the citation check, with the reason it was dropped. */
export interface RejectedEntry {
  reason: string;
  raw?: unknown;
}

export interface ParseResult {
  pairs: QAPair[];
  rejected: RejectedEntry[];
}

export type ChunkOutcomeStatus = "ok" | "failed";

/** What happened when generating pairs for one chunk during a (non-dry-run)
 * batch run — always present for every chunk actually attempted this run. */
export interface ChunkGenerationOutcome {
  chunk_id: string;
  status: ChunkOutcomeStatus;
  pairs: QAPair[];
  rejected: RejectedEntry[];
  attempts: number;
  usage?: { inputTokens: number; outputTokens: number };
  /** Present when status is "failed": either the API error after retries
   * were exhausted, or "no valid pairs" when every candidate was rejected. */
  failureReason?: string;
}

export interface TeacherRequest {
  model: string;
  maxTokens: number;
  temperature?: number | null;
  system: string;
  user: string;
}

export interface TeacherResponse {
  text: string;
  usage: { inputTokens: number; outputTokens: number };
}

/** Abstraction over "call the teacher model" — injectable so the gate never
 * touches the real Anthropic transport (see teacher.ts for the real impl,
 * and test/qa.helpers.ts for the mocks used across the test suite). */
export interface TeacherClient {
  generate(request: TeacherRequest): Promise<TeacherResponse>;
}

/** Which transport carries teacher-model calls (issue #223):
 * "claude-code-subscription" (headless `claude -p`, riding the user's
 * Claude subscription) or "anthropic-api" (the metered Claude API,
 * explicit opt-in only). See engine.ts for selection/construction and
 * claudeCodeTeacher.ts/teacher.ts for the two TeacherClient impls. */
export type EngineId = "claude-code-subscription" | "anthropic-api";

export interface PromptConfig {
  pairsPerChunk: number;
  /** Instructions injected into the prompt to keep question phrasing varied
   * across pairs (direct / scenario / comparison / terse-keyword, etc.) —
   * committed config per SPEC-APP.md §7.3, not hardcoded in the prompt. */
  diversityInstructions: string[];
}

export interface BatchConfig {
  /** Chunks processed per outer batch group. */
  size: number;
  /** Max simultaneous in-flight teacher requests. */
  maxConcurrent: number;
  /** Requests/minute cap across the whole run; 0 or omitted disables
   * rate limiting. */
  requestsPerMinute: number;
}

export interface CostConfig {
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  /** Once the running cost estimate reaches this many USD, the runner
   * stops LAUNCHING new chunks — this is not a hard cap on total spend.
   * Up to `batch.maxConcurrent` requests already in flight when the
   * ceiling is crossed are allowed to finish (the runner isolates a
   * per-chunk API call, it doesn't cancel one mid-request), so actual
   * spend can overshoot the ceiling by up to maxConcurrent chunks' worth
   * of cost. null disables the ceiling. */
  ceilingUsd: number | null;
}

export interface GenerationConfig extends PromptConfig {
  teacherModel: string;
  maxTokens: number;
  /** Only sent to the API when set — recent Claude models reject a
   * non-default temperature, so omitting it (the config default) is the
   * safe choice; see src/qa/teacher.ts. */
  temperature?: number | null;
  batch: BatchConfig;
  cost: CostConfig;
  /** Retries applied on top of the API's own retryable-error backoff (429
   * / 5xx) before a chunk is recorded as failed. */
  maxRetries: number;
  retryBaseDelayMs: number;
  /** Which teacher transport to use (issue #223). Optional so older
   * committed configs without this field still load — cli.ts's
   * resolveEngineId falls back to DEFAULT_ENGINE_ID when both this and
   * the --engine CLI flag are absent. A CLI flag, when given, always
   * overrides this. */
  engine?: EngineId;
}

export interface ProgressState {
  /** chunk_ids that produced at least one accepted pair. */
  doneChunkIds: string[];
  /** chunk_ids that were attempted and failed (API error after retries, or
   * zero valid pairs after parsing) — not retried automatically on resume. */
  failed: { chunk_id: string; reason: string }[];
  costUsd: number;
  requestCount: number;
}

export interface DryRunPlanEntry {
  chunk_id: string;
  request: TeacherRequest;
}

export interface RunResult {
  /** Outcomes for chunks actually attempted THIS invocation (excludes
   * chunks already done/failed on resume, and is empty for a dry run). */
  outcomes: ChunkGenerationOutcome[];
  progress: ProgressState;
  stoppedEarly: { reason: "cost-ceiling" } | null;
  /** Present only for dryRun: what would have been sent for every chunk. */
  dryRunPlan?: DryRunPlanEntry[];
}

export type { Chunk };
